# Generated by Django 5.0.9 on 2024-10-18 01:24

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('managed_by', models.CharField(default='manual', max_length=10)),
                ('url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('renewal_url', models.URLField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('acme_endpoint', models.URLField(blank=True, null=True)),
                ('acme_account', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=30)),
                ('common_name', models.CharField(max_length=255)),
                ('san', models.TextField(blank=True, null=True)),
                ('wildcard', models.BooleanField(default=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField()),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('fingerprint', models.CharField(max_length=255)),
                ('key_size', models.PositiveIntegerField(blank=True, null=True)),
                ('signature_algorithm', models.CharField(blank=True, max_length=50, null=True)),
                ('key_usage', models.TextField(blank=True, null=True)),
                ('extended_key_usage', models.TextField(blank=True, null=True)),
                ('revocation_status', models.BooleanField(default=False)),
                ('crl_distribution_points', models.TextField(blank=True, null=True)),
                ('ocsp_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('renewal_notification_date', models.DateField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='tenancy.tenant')),
                ('certificate_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='netbox_certificate_plugin.certificateauthority')),
            ],
            options={
                'ordering': ['expiration_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostnames', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificateHostnameRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostname_relationships', to='netbox_certificate_plugin.certificate')),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_relationships', to='netbox_certificate_plugin.hostname')),
            ],
            options={
                'unique_together': {('certificate', 'hostname')},
            },
        ),
    ]