# Generated by Django 5.0.9 on 2024-10-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificate_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['expiration_date', 'common_name']},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
    ]